### ISSUE TITLE
Link shops to contacts

### ISSUE THREAD

**Issue by michielbdejong** [solid/money-pane#4]
The current code is a very bare skeleton that [imports statements from a csv download from your bank](https://github.com/solid/money-pane#import-transaction-statements-from-your-bank).

I haven't written the code yet to store it as RDF since I'm still finding out which ontology / predicates to use.

But one thing I want to do next is to create one contact per shop (transaction counterparty) that appears on the bank statement.

For insight in personal finance it would then suffice to group these contacts into themes ("Groceries", "Utilities" etc).

**Comment by michielbdejong** [comment]
The [MCC codes](https://fs.fldfs.com/iwpapps/pcard/docs/MCCs.pdf) should also help for BEA transactions

**Comment by michielbdejong** [comment]
The shops should be uniquely identified, so I guess it makes sense to have a special Shops addressbook for parsing BEA transactions. The full name could be the trimmed part before the `>`. for instance for this transaction description:
```
'Gumus Market          >UTRECHT  11.10.2020 14U35 KV008 8KG2YV   MCC:5499 Contactloze betaling NLNEDERLAND'
```
The following contact could be automatically added to the user's 'Shops' address book:
* full name: 'Gumus Market'
* location: 'Utrecht'
* groups: 'MISC FOOD STORES - SPECIALTY MARKETS & CONVENIENCE (MCC 5499)'

**Comment by michielbdejong** [comment]
What I would need from solid-logic is methods to:
* get or create an addressbook called 'Shops'
* in there, get or create a contact called 'Gumus Market', with location 'Utrecht', and member of group MCC-5499
* also create group MCC-5499 if it doesn't exist

I think there should be one history per shop  (purchase + settlement pairs, so the balance there stays at zero), plus on for the bank account whose transaction history was imported (settlement only so balance there goes down)
(settlement transaction only)

**Comment by MikiDi** [comment]
If you'd be open to sharing some of your decision-making process regarding which ontology to use, please do so! I'd be very interested (in contributing later on)!

**Comment by michielbdejong** [comment]
Continued in https://solidos.solidcommunity.net/Team/2021/money-pane-project/money%20pane/state.ttl#Iss1610015239190

**Comment by michielbdejong** [comment]
@MikiDi Good to hear! We can discuss in the weekly Solid OS meeting https://solidos.solidcommunity.net/Team/2020/schedule/solidos-schedule.html
